apiVersion: v1

kind: Service

metadata:
  name: db
  labels:
    name: postgres-db
    for: votingapp-viapods

spec:
  ports:
    - targetPort: 5432
      port: 5432

  selector:
    name: postgres-pod
    for: votingapp-viapods

