apiVersion: v1

kind: Service

metadata:
  name: redis-service
  labels:
    name: redis-service
    for: votingapp-viapods

spec:
  ports:
    - targetPort: 6379
      port: 6379

  selector:
    name: redis-pod
    for: votingapp-viapods

