apiVersion: v1

kind: Pod

metadata:
  name: resultapp-pod
  labels:
    name: resultapp-pod
    for: votingapp-viapods

spec:
  containers:
    - name: resultapp-image
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80



