apiVersion: v1

kind: Service

metadata:
  name: votingapp-service
  labels:
    name: myvoting-app
    for: votingapp-viapods

spec:
  type: LoadBalancer

  ports:
    - targetPort: 80
      port: 80

  selector:
    name: myvoting-app
    for: votingapp-viapods


